# -*- coding: utf-8 -*-

# How many seconds to wait for the proxy to make a connection.
# The higher this number, the longer the check will take
# and the more proxies you will receive.
TIMEOUT = 5

# Maximum concurrent connections.
# Don't set higher than 900, please.
MAX_CONNECTIONS = 900

# Set to False to sort proxies alphabetically.
SORT_BY_SPEED = True

# Path to the folder where the proxy folders will be saved.
# Leave the quotes empty to save the proxies to the current directory.
SAVE_PATH = ""

# Enable which proxy folders to create.
# Set to False to disable.

# Proxies with any anonymity level.
PROXIES = True
# Anonymous proxies.
PROXIES_ANONYMOUS = True
# Same as PROXIES, but including exit-node's geolocation.
# Geolocation format is ip:port::Country::Region::City
PROXIES_GEOLOCATION = True
# Same as PROXIES_GEOLOCATION, but including exit-node's geolocation.
PROXIES_GEOLOCATION_ANONYMOUS = True


# PROTOCOL - whether to enable checking certain protocol proxies (True or False).
# PROTOCOL_SOURCES - proxy lists URLs.
HTTP = True
HTTP_SOURCES = (
    "https://api.proxyscrape.com/v2/?request=getproxies&protocol=http",
    "https://openproxy.space/list/http",
    "https://raw.githubusercontent.com/almroot/proxylist/master/list.txt",
    "https://raw.githubusercontent.com/clarketm/proxy-list/master/proxy-list-raw.txt",
    "https://raw.githubusercontent.com/hendrikbgr/Free-Proxy-Repo/master/proxy_list.txt",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-http%2Bhttps.txt",
    "https://raw.githubusercontent.com/mmpx12/proxy-list/master/http.txt",
    "http://www.004388.com/ip/index_2.html",
    "http://www.004388.com/ippt/index_2.html",
    "http://www.004388.com/ipgw/index_2.html",
    "http://www.004388.com/ipgwtm/index_2.html",
    "http://www.004388.com/socks/index_2.html",
    "http://www.004388.com/ip/",
    "http://www.004388.com/ippt/",
    "http://www.004388.com/ipgw/",
    "http://www.004388.com/ipgwtm/",
    "http://www.004388.com/socks/",
    "http://01hitfaker.blogspot.com/feeds/posts/default?alt=rss",
    "http://0dayproxies.blogspot.com/feeds/posts/default?alt=rss",
    "http://1000freeanonymousproxy.blogspot.com/feeds/posts/default?alt=rss",
    "http://100filmovru.blog.fc2.com/",
    "http://100proxygratis.blogspot.com/feeds/posts/default?alt=rss",
    "https://1110111.com/forumdisplay.php?fid=78",
    "http://123proxies.blogspot.com/",
    "http://1337spam.blogspot.com/feeds/posts/default?alt=rss",
    "http://139239123912391.my1.ru/",
    "http://13i13.blogspot.com/feeds/posts/default?alt=rss",
    "http://174.139.241.42/1.txt",
    "http://174.139.241.42/yahoo/lists/check_report.txt",
    "http://185.81.158.218/http.txt",
    "http://www.1887.sd.cn/xw/index.asp?id=1&page=1",
    "http://1db2.in/?s=proxy",
    "http://www.1tzc.com/shenbodaili/",,
    "http://1viraldata.blogspot.com/feeds/posts/default?alt=rss",
    "http://2013-proxy-list.blogspot.com/feeds/posts/default?alt=rss",
    "http://22xxbb.lofter.com/",
    "http://24hourshacking.blogspot.com/feeds/posts/default?alt=rss",
    "http://2freesocks5list.blogspot.com/feeds/posts/default?alt=rss",
    "http://31f.cn/http-proxy/",
    "http://31f.cn/https-proxy/",
    "http://31f.cn/socks-proxy/",
    "http://www.3464.com/data/Proxy/Http/",
    "http://www.3464.com/data/Proxy/Socks5/",
    "http://3doyunindir.blogspot.com/feeds/posts/default?alt=rss",
    "http://www.3stuff.site/category/free-proxy/feed/",
    "http://3xdr.blogspot.com/feeds/posts/default?alt=rss",
    "http://3zun.com/",
    "http://4r.ketnoitatca.net/showthread.php/170890-Share-Proxy-server-Proxies-list-update-daily/page9999999",
    "http://4youngsterz.blogspot.com/feeds/posts/default?alt=rss",
    "http://50kproxies.com/category/proxy-list/",
    "http://www.51140.net/proxy/",
    "http://55face.blogspot.com",
    "http://64box.blogspot.com/feeds/posts/default?alt=rss",
    "http://www.66ip.cn/mo.php?tqsl=1000",
    "http://www.6brj.com/free",
    "http://7519llsz.cn/llsz/av7xc7b7d9j7x3a2s6f54g.txt",
    "http://7proxy.blogspot.com/feeds/posts/default?alt=rss",
    "http://www.89ip.cn/tiqu.php?sxb=&tqsl=3000&ports=&ktip=&xl=on&submit=%CC%E1++%C8%A1",
    "http://8proxy.blogspot.com/feeds/posts/default?alt=rss",
    "http://98.126.108.155/1.txt",
    "http://98.126.108.155/google/lists/check_report.txt",
    "http://98.126.108.155/yahoo/lists/check_report.txt",
    "http://98.126.108.155/yahoo/tmp/sortspeed.txt",
    "http://98.126.61.179/yahoo/lists/check_report.txt",
    "http://98.126.61.179/1.txt",
    "http://aa8.narod.ru/index/0-11",
    "http://aa8.narod.ru/index/0-10",
    "http://aa8.narod.ru/index/0-9",
    "http://aa8.narod.ru/index/0-8",
    "http://ab57.ru/downloads/proxylist.txt",
    "http://absentius.narod.ru/",
    "http://accforfree.blogspot.com/feeds/posts/default?alt=rss",
    "http://actualproxy.blogspot.com/feeds/posts/default?alt=rss",
    "http://adan82222.blogspot.com/feeds/posts/default?alt=rss",
    "http://adminsarhos.blogspot.com/feeds/posts/default?alt=rss",
    "http://www.admintuan.com/",
    "http://advanceauto-show.blogspot.com/feeds/posts/default?alt=rss",
    "http://www.agarboter.ga/Proxy/",
    "http://agarioproxys.blogspot.com/feeds/posts/default?alt=rss",
    "http://agarproxy.tk/ip/1.php",
    "http://agarproxy.tk/ip/2.php",
    "http://agarproxy.tk/ip/3.php",
    "http://agarproxy.tk/ip/4.php",
    "http://ahmadas120873.blogspot.com/feeds/posts/default?alt=rss",
    "http://ahmadqoisja09.blogspot.com/feeds/posts/default?alt=rss",
    "http://aimeegracecatering.blogspot.com/feeds/posts/default?alt=rss",
    "http://aircrack.kl.com.ua/all.txt",
    "http://www.ajshw.net/news/?list_20.html",
    "http://akatsukihackblog.blogspot.com/feeds/posts/default?alt=rss",
    "http://alexa.lr2b.com/proxylist.txt",
    "http://aliveproxies.com/ipproxy/page/1/",
    "http://aliveproxies.com/ipproxy/transparent/page/1/",
    "http://aliveproxies.com/pages/page-scrapebox-proxies/",
    "http://aliveproxies.com/ipproxy/elite/page/1/",
    "http://aliveproxies.com/ipproxy/anonymous/page%/page%/",
    "http://alivevpn.blogspot.com/feeds/posts/default?alt=rss",
    "http://alldayproxy.blogspot.com/feeds/posts/default?alt=rss",
    "http://amega.blogfree.net/?f=1101173",
    "http://amisauvveryspecial.blogspot.com/feeds/posts/default?alt=rss",
    "http://www.amusetech.net/proxys.txt",
    "http://android-amiral.blogspot.com/feeds/posts/default?alt=rss",
    "http://android-ful.blogspot.com/feeds/posts/default?alt=rss",
    "http://andrymc4.blogspot.com/feeds/posts/default?alt=rss",
    "http://anondwahyu.blogspot.com/feeds/posts/default?alt=rss",
    "https://anonfreeproxy.blogspot.com/feeds/posts/default?alt=rss",
    "http://anon-hackers.forumfree.it/?f=11363412",
    "http://anonimseti.blogspot.com/feeds/posts/default?alt=rss",
    "http://anonproxylist.blogspot.com/feeds/posts/default?alt=rss",
    "http://www.anonproxylist.com/feed/",
    "http://anonymouscyberteamact.blogspot.com/feeds/posts/default?alt=rss",
    "http://feeds.feedburner.com/AnonymousDailyProxyList",
    "http://anonymousproxies007.blogspot.com/feeds/posts/default?alt=rss",
    "http://anonymous-proxy.blogspot.com/feeds/posts/default?alt=rss",
    "http://anonymousproxyblog.blogspot.com/feeds/posts/default?alt=rss",
    "http://www.antynet.pl/index.php/feed/",
    "http://anyelse.com/Index.aspx?p=1",
    "http://apexgeeky.blogspot.com/feeds/posts/default?alt=rss",
    "http://api.foxtools.ru/v2/Proxy.txt",
    "http://api.good-proxies.ru/get.php?free=",
    "http://applebaby2013.blogspot.com/feeds/posts/default?alt=rss",
    "http://ar51.eu/forum/222-proxy/",
    "http://arianatorleaks.com/list/proxy.txt",
    "http://www.arpun.com/article/list_1_319.html",
    "http://artgameshop.ru/proxy/api/proxylist.php",
    "http://asdfg3ffasdasdasd.blogspot.com/feeds/posts/default?alt=rss",
    "http://asifameerbakhsh.blogspot.com/feeds/posts/default?alt=rss",
    "http://www.askimiz.net/kategori/genel",
    "http://astra.bbbv.ru/index.php?showforum=4",
    "http://asua.esy.es/ProxyServers/proxy.txt",
    "http://www.atcpu.com/thread/123?type=179",
    "http://www.atesclup.com/forum/guencel-proxy-listesi.285/",
    "http://www.atnteam.com/forumdisplay.php?20-Discussions-about-anonymity",
    "http://www.atnteam.com/forumdisplay.php?21-Socks-Proxy",
    "http://www.atnteam.com/forumdisplay.php?22-HTTP-Proxy",
    "http://atomintersoft.com/free_socks5_proxy_list",
    "http://atomintersoft.com/free_proxy_list",
    "http://atomintersoft.com/transparent_proxy_list",
    "http://atomintersoft.com/anonymous_proxy_list",
    "http://atomintersoft.com/high_anonymity_elite_proxy_list",
    "https://autoproxyblog.wordpress.com/feed/",
    "http://avto-alberto.avtostar.si/avtostar/proxy_list_1.txt",
    "http://avto-alberto.avtostar.si/avtostar/proxy_list_2.txt",
    "http://avto-alberto.avtostar.si/avtostar/proxy_list_3.txt",
    "http://awmproxy.cn/freeproxy.php",
    "http://awmproxy.com/freeproxy_XXXXXXXXX.txt",
    "http://awmproxy.com.ua/",
    "http://awmproxy.de/index.php",
    "http://awmproxy.net/",
    "http://www.aw-reliz.ru/index.php/board,7.0.html",
    "https://bacasimpel.blogspot.com/feeds/posts/default?alt=rss",
    "http://backtrack-gr0up.blogspot.com/feeds/posts/default?alt=rss",
    "http://backtrack-group.blogspot.com/feeds/posts/default?alt=rss",
    "http://baglanforum.10tr.net/syndication.php?type=atom1.0&fid=111",
    "http://baglanforum.10tr.net/syndication.php?fid=112",
    "http://baglanforum.10tr.net/syndication.php?fid=113",
    "http://baglanforum.10tr.net/syndication.php?fid=118",
    "http://www.bagnets.cn/bag/dailiIP/guonaIPdaili/",
    "http://www.baizhongso.com/ipShow.aspx?id=7972",
    "http://www.baizhongsou.com/default.aspx",
    "http://www.bali-xp.com/feeds/posts/default?alt=rss",
    "http://base.4rumer.com/f17-socks-proxy",
    "http://base.4rumer.com/f18-http-proxy",
    "http://bbhfdownloads.blogspot.com/feeds/posts/default?alt=rss",
    "http://bbs.crsky.com/simple/index.php?f80.html",
    "http://bdaccess24.blogspot.com/feeds/posts/default?alt=rss",
    "https://beatemailmass9947.wordpress.com/feed/",
    "http://beautydream.spb.ru/category/hvastiki/feed/",
    "http://bestallproxy.blogspot.com/feeds/posts/default?alt=rss",
    "http://bestblackhatforum.com/Forum-Proxies-and-VPN-Section",
    "http://bestblackhattips.blogspot.com/feeds/posts/default?alt=rss",
    "http://best-hacker.ru/proksi-svezhak/?s=%D0%BF%D1%80%D0%BE%D0%BA%D1%81%D0%B8",
    "http://bestpollitra.com/lending/prxsRaw/all/",
    "http://bestpremiumproxylist.blogspot.com/feeds/posts/default?alt=rss",
    "http://bestproxiesandsocks.blogspot.com/feeds/posts/default?alt=rss",
    "http://bestproxiesofworld.blogspot.com/feeds/posts/default?alt=rss",
    "http://best-proxy.com/english/index.php?p=1",
    "http://best-proxylist.blogspot.com/feeds/posts/default?alt=rss",
    "http://bestproxylist4you.blogspot.com/feeds/posts/default?alt=rss",
    "http://bhfreeproxies.blogspot.com/feeds/posts/default?alt=rss",
    "http://www.bigdaili.com/dailiip/1/1.html",
    "http://www.bigdaili.com/dailiip/2/1.html",
    "http://www.bigdaili.com/dailiip/3/1.html",
    "http://www.bigdaili.com/dailiip/4/1.html",
    "http://biskutliat.blogspot.com/feeds/posts/default?alt=rss",
    "https://bitorder.ru/forumdisplay.php?26-Socks5",
    "http://blackhatforum.co/forumdisplay.php?17-Proxies",
    "http://blackhatland.com/forumdisplay.php?fid=68",
    "http://www.blackhatprivate.com/index.php?/forum/97-proxies-section/",
    "http://www.blackhatprotools.org/forumdisplay.php?18-Proxies",
    "http://www.blackhatseo.pl/forum/4-pozycjonowanie-w-google/",
    "http://blackhatseocommunity.com/f20/",
    "http://blackhatviet.com/forumdisplay.php/24-Hosting-VPS-Proxy-Socks",
    "http://black-socks24.blogspot.com/feeds/posts/default?alt=rss",
    "http://blackxpirate.blogspot.com/feeds/posts/default?alt=rss",
    "http://blast.hk/forums/32/",
    "http://www.blizzleaks.net/",
    "http://blog.bafoed.ru/feed/",
    "http://blog.baotuoitredoisong.com/search/label/Socks%20Proxy",
    "http://blog.crackitindonesia.com/search?q=proxy",
    "http://blog.donews.com/kemon/feed/",
    "http://blog.fzcnjp.com/proxy",
    "http://blog.i.ua/user/616175/",
    "http://blog.kuaidaili.com/feed",
    "http://blog.mobilsohbetodalari.org/feed",
    "http://blog.sina.com.cn/rss/5075816935.xml",
    "http://blogprojesitr.blogspot.com/feeds/posts/default?alt=rss",
    "http://blogspotproxy.blogspot.com/feeds/posts/default?alt=rss",
    "http://www.blue-hosting.biz/",
    "http://boltonnewyork.blogspot.com/feeds/posts/default?alt=rss",
    "https://www.boomplace.com/index.php/forum/mixed/282-proxy-liste-100-ips-taeglich-neu?start=99999999",
    "http://boosterbotsforum.com/index.php?p=/categories/freebies-giveaways",
    "http://botgario.ml/proxy/",
    "http://brainviewhackers.blogspot.com/feeds/posts/default?alt=rss",
    "http://brazilproxies.blogspot.com/feeds/posts/default?alt=rss",
    "http://brothers-download.mihanblog.com/post/rss",
    "http://bsproxy.blogspot.com/feeds/posts/default?alt=rss",
    "http://www.bulkmoneyforum.com/share-your-free-stuff-free-services-request-here-if-u-need-something/12768-good-working-checked-live-proxies-999999.html",
    "http://buondon.info/forums/sock-live.143.html",
    "http://www.buyproxy.ru/free-proxies/%D0%9D%D0%B5%D1%82_socks/",
    "http://buytrafficus.blogspot.com/feeds/posts/default?alt=rss",
    "http://bworm.vv.si/",
    "http://www.cannabis-samen-hanfsamen.de/",
    "http://www.captchapanel.blogspot.com/feeds/posts/default?alt=rss",
    "http://caratrikblogger.blogspot.com/feeds/posts/default?alt=rss",
    "http://carder.site/forumdisplay.php?f=58",
    "http://carderparadise.com/forumdisplay.php?14-Security-Services",
    "https://cardersforum.se/forum55/",
    "https://cardersforum.ws/forum55/",
    "http://www.caretofun.net/free-proxies-and-socks/",
    "http://cc-ppfresh.blogspot.com/feeds/posts/default?alt=rss",
    "http://cdn.vietso1.com/forums/proxy-socks.63/",
    "https://cfud.biz/lending/prxsDownload/all/",
    "http://www.changeips.com/",
    "http://www.chaojirj.com/daili/",
    "http://www.chatles.net/kategori/irc-proxy/feed",
    "http://cheap-flights-to-dubai.blogspot.com/feeds/posts/default?alt=rss",
    "http://cheap-offers-online.com/feed/",
    "http://checkerproxy.net/",
    "http://checkproxylist.blogspot.com/feeds/posts/default?alt=rss",
    "http://check-proxylist.blogspot.com/feeds/posts/default?alt=rss",
    "http://www.checkyounow.com/
    "http://www.chemip.net/proxyip.html",
    "https://chenqu.wordpress.com/tag/proxy/
    "http://china-eliteproxy.blogspot.com/feeds/posts/default?alt=rss",
    "http://chinaproxies.blogspot.com/feeds/posts/default?alt=rss",
    "https://chinaproxylist.wordpress.com/feed/",
    "http://chingachgook.net/my-servisy/proxy",
    "http://chk.gblknjng.com/socks.txt",
    "http://www.chupadrak.i8.com/",
    "http://clientn.autohideip.com/update/",
    "http://clientn.easy-hideip.com/update/",
    "http://clientn.platinumhideip.com/update/?ACTION=Update",
    "http://clientn.platinumhideip.com/update/?ACTION=Update&51823&PID=PHI&SN=&MCD=0000000000CD1A40&UNL=&LANG=English&DAY=0&RUNTIME=0&VER=03000406&SVER=0&WVER=5_1_Service",
    "http://clientn.real-hide-ip.com/update/?ACTION=Update",
    "http://clientn.superhideip.com/update/?ACTION=Update&14783&PID=SHI&SN=&MCD",
    "http://clientn.surfanonymous-free.com/update/?ACTION=Update&27232&PID=SAF&SN=&MCD=000000001C35B5B7&UNL=&LANG=English&DAY=0&RUNTIME=0&VER=02010502&SVER=0&WVER=6_1_Service",
    "https://raw.githubusercontent.com/mmpx12/proxy-list/master/https.txt",
    "https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt",
    "https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/proxies.txt",
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt",
    "https://raw.githubusercontent.com/UserR3X/proxy-list/main/http%2Bs.txt",
    "https://raw.githubusercontent.com/Volodichev/proxy-list/main/http.txt",
    "https://www.proxy-list.download/api/v1/get?type=http",
    "https://www.proxy-list.download/api/v1/get?type=https",
    "https://www.proxyscan.io/download?type=http",
    "https://www.proxyscan.io/download?type=https",
)
SOCKS4 = True
SOCKS4_SOURCES = (
    "https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks4",
    "https://openproxy.space/list/socks4",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks4.txt",
    "https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks4.txt",
    "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt",
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt",
    "https://raw.githubusercontent.com/UserR3X/proxy-list/main/socks4.txt",
    "https://www.proxy-list.download/api/v1/get?type=socks4",
    "https://www.proxyscan.io/download?type=socks4",
)
SOCKS5 = True
SOCKS5_SOURCES = (
    "https://api.proxyscrape.com/v2/?request=getproxies&protocol=socks5",
    "https://openproxy.space/list/socks5",
    "https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt",
    "https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt",
    "https://raw.githubusercontent.com/manuGMG/proxy-365/main/SOCKS5.txt",
    "https://raw.githubusercontent.com/mmpx12/proxy-list/master/socks5.txt",
    "https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt",
    "https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt",
    "https://raw.githubusercontent.com/UserR3X/proxy-list/main/socks5.txt",
    "https://www.proxy-list.download/api/v1/get?type=socks5",
    "https://www.proxyscan.io/download?type=socks5",
)
